# Generated by Django 5.2.6 on 2026-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_subject_exam_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
