# Generated by Django 5.2.6 on 2026-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_enrollment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
