# Generated by Django 5.2.6 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_marks_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markshistory',
            name='new_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='markshistory',
            name='old_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
