# Generated by Django 5.2.6 on 2026-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_markshistory_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='at1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='at2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='at3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='at4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='est',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='external',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mid1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mid2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mid3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
