# Generated by Django 5.2.6 on 2026-04-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_alter_marks_at1_alter_marks_at2_alter_marks_at3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='is_absent',
        ),
    ]
