# Generated by Django 5.2.6 on 2026-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_remove_marks_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('MARK_UPDATE', 'Mark Update'), ('BATCH_PROMOTE', 'Batch Promote'), ('BATCH_CREATE', 'Batch Create'), ('BATCH_COMPLETE', 'Batch Complete'), ('SUBJECT_CREATE', 'Subject Create'), ('PDF_EXPORT', 'PDF Export'), ('BULK_UPLOAD', 'Bulk Upload'), ('NOTIFICATION', 'Notification'), ('ELECTIVE_ASSIGN', 'Elective Assignment')], max_length=30),
        ),
    ]
