# Generated by Django 5.2.6 on 2026-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='external_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marks',
            name='internal_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marks',
            name='mid1_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marks',
            name='mid2_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marks',
            name='mid3_absent',
            field=models.BooleanField(default=False),
        ),
    ]
