# Generated by Django 5.2.6 on 2026-04-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_marks_external_absent_marks_internal_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markshistory',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
