# Generated by Django 5.2.6 on 2026-04-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_markshistory_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='est_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='markshistory',
            name='was_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject', 'semester', 'batch')},
        ),
    ]
