# Generated by Django 5.2.6 on 2026-04-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_marks_est_absent_markshistory_was_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
